#### Importing the libraries

In [219]:
# link :https://archive.ics.uci.edu/ml/datasets/ecoli
import tensorflow as tf
import numpy as np
import csv

#### Importing Data

In [216]:
raw_data = open('ecoli.csv', 'rt')
reader = csv.reader(raw_data, delimiter=',', quoting=csv.QUOTE_NONE)
data = list(reader)
data = np.array(data)
data = data[:,2: -2].astype(float)

In [217]:
print(data)
print(np.shape(data))

[[0.29 0.48 0.5  0.56 0.24]
 [0.4  0.48 0.5  0.54 0.35]
 [0.4  0.48 0.5  0.49 0.37]
 ...
 [0.6  0.48 0.5  0.44 0.39]
 [0.61 0.48 0.5  0.42 0.42]
 [0.74 0.48 0.5  0.31 0.53]]
(336, 5)


#### Data Processing
- 
    Sequences are made into a square image of closest binary number to the the ceiling of the root of the length


In [218]:
rows, columns = np.shape(data)
sqrt_col = int(np.ceil(np.sqrt(columns)))
processed_data = np.zeros([rows, 3, 3])
data_ = np.zeros([rows, 3*3])

for i in range(rows):
#     data[i] = (data[i] - np.mean(data[i]))
    data_[i] = np.append(data[i], np.zeros(3*3 - columns))

    
for i in range(rows):
    for j in range(sqrt_col):
            processed_data[i,j,:] = data_[i, j * 3 : (j+1)*3]

In [195]:
processed_data[0]

array([[0.29, 0.48, 0.5 ],
       [0.56, 0.24, 0.  ],
       [0.  , 0.  , 0.  ]])

#### Generator

In [196]:
def gen_model(input_shape):
    
    Input_1= tf.keras.layers.Input(shape = input_shape)
    
    model = tf.keras.layers.Conv2D(3, (3,3), activation='relu', input_shape=input_shape,kernel_regularizer=tf.keras.regularizers.l2(2e-4), padding ='same')(Input_1)
    model = tf.keras.layers.BatchNormalization()(model)
    
    model = tf.keras.layers.Conv2D(4, (4,4), activation='relu', input_shape=input_shape,kernel_regularizer=tf.keras.regularizers.l2(2e-4), padding ='same')(model)
    model = tf.keras.layers.BatchNormalization()(model)
    
    model = tf.keras.layers.Conv2D(4, (4,4), activation='relu', input_shape=input_shape,kernel_regularizer=tf.keras.regularizers.l2(2e-4), padding ='same')(model)
    model = tf.keras.layers.BatchNormalization()(model)
    
    model = tf.keras.layers.Conv2D(1, (4,4), activation='tanh', input_shape=input_shape,kernel_regularizer=tf.keras.regularizers.l2(2e-4), padding ='same')(model)
    output = tf.keras.layers.BatchNormalization()(model)
    
    model = tf.keras.models.Model(inputs=Input_1, outputs = output, name = 'generator')
    
    return model

In [197]:
gen = gen_model((3,3,1))

In [198]:
gen.summary()

Model: "generator"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_40 (InputLayer)        [(None, 3, 3, 1)]         0         
_________________________________________________________________
conv2d_94 (Conv2D)           (None, 3, 3, 3)           30        
_________________________________________________________________
batch_normalization_94 (Batc (None, 3, 3, 3)           12        
_________________________________________________________________
conv2d_95 (Conv2D)           (None, 3, 3, 4)           196       
_________________________________________________________________
batch_normalization_95 (Batc (None, 3, 3, 4)           16        
_________________________________________________________________
conv2d_96 (Conv2D)           (None, 3, 3, 4)           260       
_________________________________________________________________
batch_normalization_96 (Batc (None, 3, 3, 4)           16

#### Discriminator

In [199]:
def discrim_model(input_shape):
    
    Input_1= tf.keras.layers.Input(shape = input_shape)
    
    model = tf.keras.layers.Conv2D(3, (4,4), activation='relu', input_shape=input_shape,kernel_regularizer=tf.keras.regularizers.l2(2e-4), padding ='same')(Input_1)
    model = tf.keras.layers.BatchNormalization()(model)

    model = tf.keras.layers.Conv2D(3, (2,2), activation='relu', input_shape=input_shape,kernel_regularizer=tf.keras.regularizers.l2(2e-4), padding ='same')(model)
    model = tf.keras.layers.BatchNormalization()(model)
    
    model = tf.keras.layers.Conv2D(3, (2,2), activation='relu', input_shape=input_shape,kernel_regularizer=tf.keras.regularizers.l2(2e-4), padding ='same')(model)
    model = tf.keras.layers.BatchNormalization()(model)

    model = tf.keras.layers.Flatten()(model)
    
    output = tf.keras.layers.Dense(1, activation = 'sigmoid')(model)
    
    model = tf.keras.models.Model(inputs=Input_1, outputs = output, name = 'discriminator')
    
    return model



In [200]:
discrim = discrim_model((3,3,1))

In [201]:
discrim.summary()

Model: "discriminator"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_41 (InputLayer)        [(None, 3, 3, 1)]         0         
_________________________________________________________________
conv2d_98 (Conv2D)           (None, 3, 3, 3)           51        
_________________________________________________________________
batch_normalization_98 (Batc (None, 3, 3, 3)           12        
_________________________________________________________________
conv2d_99 (Conv2D)           (None, 3, 3, 3)           39        
_________________________________________________________________
batch_normalization_99 (Batc (None, 3, 3, 3)           12        
_________________________________________________________________
conv2d_100 (Conv2D)          (None, 3, 3, 3)           39        
_________________________________________________________________
batch_normalization_100 (Bat (None, 3, 3, 3)         

#### Creating the entire network

In [202]:
# Discriminator
optimizer_discrim = tf.keras.optimizers.Adam(0.0002, 0.5)
discriminator = discrim_model((3, 3, 1))
discriminator.compile(loss='binary_crossentropy',optimizer=optimizer_discrim,metrics=['accuracy'])

In [203]:
# Generator
generator = gen_model((3,3,1))

In [204]:
# Combined Network
inp = tf.keras.Input((3,3,1))
gen = generator(inp)
optimizer_gen = tf.keras.optimizers.Adam(0.0002, 0.5)
discriminator.trainable = False
discrim = discriminator(gen)
gan = tf.keras.Model(inp, discrim)
gan.compile(loss='binary_crossentropy', optimizer=optimizer_gen,metrics=['accuracy'])

In [205]:
# Summary
gan.summary()

Model: "model_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_44 (InputLayer)        [(None, 3, 3, 1)]         0         
_________________________________________________________________
generator (Model)            (None, 3, 3, 1)           599       
_________________________________________________________________
discriminator (Model)        (None, 1)                 193       
Total params: 792
Trainable params: 575
Non-trainable params: 217
_________________________________________________________________


#### Training

In [206]:
# Training Parameters
batch_size = 336
iterations = 10000

# Training Data
X_train = np.expand_dims(processed_data, axis = 3)

# Labels
true_label = np.ones((batch_size, 1))
fake_label = np.zeros((batch_size, 1))

# Training
for epoch in range(iterations):
    
    # Random sample of data
    random_indices = np.random.randint(0, X_train.shape[0], batch_size)
    discrim_data = X_train[random_indices]
    gaussian = np.random.normal(0.5, 0.25, (batch_size, X_train.shape[1], X_train.shape[2], 1))
    
    # Training the discriminator
      
    discrim_loss_real = discriminator.train_on_batch(discrim_data, true_label)
    generated_data = generator.predict(gaussian)
    discriminator_loss_real = discriminator.train_on_batch(discrim_data, true_label)
    discriminator_loss_fake = discriminator.train_on_batch(generated_data, fake_label)
    discriminator_loss_total = 0.5 * np.add(discrim_loss_real, discriminator_loss_fake)
    
    # Training the gan
    g_loss = gan.train_on_batch(gaussian, true_label)
    
    print('Epoch:', epoch, '| Discrim_l_real:', discriminator_loss_real, '| Discrim_l_fake:', discriminator_loss_fake, '| Gan_l:', g_loss)

Epoch: 0 | Discrim_l_real: [0.47129872, 0.86011904] | Discrim_l_fake: [0.47140706, 0.75] | Gan_l: [0.722258, 0.6577381]
Epoch: 1 | Discrim_l_real: [0.4537199, 0.89285713] | Discrim_l_fake: [0.57652694, 0.57738096] | Gan_l: [0.73360044, 0.6160714]
Epoch: 2 | Discrim_l_real: [0.4355446, 0.9285714] | Discrim_l_fake: [0.7797111, 0.45833334] | Gan_l: [0.7315161, 0.6220238]
Epoch: 3 | Discrim_l_real: [0.42821127, 0.9166667] | Discrim_l_fake: [0.9681279, 0.37202382] | Gan_l: [0.7207465, 0.6547619]
Epoch: 4 | Discrim_l_real: [0.41476953, 0.9464286] | Discrim_l_fake: [0.9939886, 0.35119048] | Gan_l: [0.71739376, 0.66071427]
Epoch: 5 | Discrim_l_real: [0.40668693, 0.94345236] | Discrim_l_fake: [0.9744414, 0.3065476] | Gan_l: [0.74152094, 0.65178573]
Epoch: 6 | Discrim_l_real: [0.39366114, 0.94345236] | Discrim_l_fake: [0.9830702, 0.26488096] | Gan_l: [0.7094457, 0.68154764]
Epoch: 7 | Discrim_l_real: [0.39363658, 0.9404762] | Discrim_l_fake: [1.0058854, 0.24107143] | Gan_l: [0.7024486, 0.6607142

Epoch: 65 | Discrim_l_real: [0.19228606, 1.0] | Discrim_l_fake: [0.36238235, 0.9970238] | Gan_l: [0.5630705, 0.7708333]
Epoch: 66 | Discrim_l_real: [0.19256537, 1.0] | Discrim_l_fake: [0.35745844, 1.0] | Gan_l: [0.5735725, 0.75595236]
Epoch: 67 | Discrim_l_real: [0.18893743, 1.0] | Discrim_l_fake: [0.35572836, 0.9970238] | Gan_l: [0.5840608, 0.7708333]
Epoch: 68 | Discrim_l_real: [0.183904, 1.0] | Discrim_l_fake: [0.3484122, 1.0] | Gan_l: [0.5721185, 0.7291667]
Epoch: 69 | Discrim_l_real: [0.18565348, 1.0] | Discrim_l_fake: [0.35298553, 0.9970238] | Gan_l: [0.55795556, 0.76488096]
Epoch: 70 | Discrim_l_real: [0.18651095, 1.0] | Discrim_l_fake: [0.34573042, 0.9970238] | Gan_l: [0.5442606, 0.7589286]
Epoch: 71 | Discrim_l_real: [0.1863276, 1.0] | Discrim_l_fake: [0.33725458, 1.0] | Gan_l: [0.5528639, 0.7529762]
Epoch: 72 | Discrim_l_real: [0.1859529, 1.0] | Discrim_l_fake: [0.33439606, 0.99404764] | Gan_l: [0.56820154, 0.7380952]
Epoch: 73 | Discrim_l_real: [0.17935425, 1.0] | Discrim_l_

Epoch: 138 | Discrim_l_real: [0.11212751, 1.0] | Discrim_l_fake: [0.19626008, 1.0] | Gan_l: [0.45297062, 0.8244048]
Epoch: 139 | Discrim_l_real: [0.111056626, 1.0] | Discrim_l_fake: [0.1947208, 0.9970238] | Gan_l: [0.43446174, 0.8244048]
Epoch: 140 | Discrim_l_real: [0.113953084, 1.0] | Discrim_l_fake: [0.1895377, 1.0] | Gan_l: [0.4402546, 0.8244048]
Epoch: 141 | Discrim_l_real: [0.11596354, 1.0] | Discrim_l_fake: [0.18708718, 1.0] | Gan_l: [0.42315295, 0.8422619]
Epoch: 142 | Discrim_l_real: [0.11783767, 1.0] | Discrim_l_fake: [0.1864026, 1.0] | Gan_l: [0.41378987, 0.8333333]
Epoch: 143 | Discrim_l_real: [0.11262507, 1.0] | Discrim_l_fake: [0.18943189, 1.0] | Gan_l: [0.4241275, 0.8333333]
Epoch: 144 | Discrim_l_real: [0.11228122, 1.0] | Discrim_l_fake: [0.18445526, 0.9970238] | Gan_l: [0.43342173, 0.81845236]
Epoch: 145 | Discrim_l_real: [0.10759127, 1.0] | Discrim_l_fake: [0.19116718, 0.99404764] | Gan_l: [0.42718127, 0.81845236]
Epoch: 146 | Discrim_l_real: [0.111499906, 1.0] | Disc

Epoch: 208 | Discrim_l_real: [0.075160846, 1.0] | Discrim_l_fake: [0.20300575, 0.9494048] | Gan_l: [0.25745222, 0.97321427]
Epoch: 209 | Discrim_l_real: [0.073712446, 1.0] | Discrim_l_fake: [0.18754742, 0.95238096] | Gan_l: [0.26682726, 0.95238096]
Epoch: 210 | Discrim_l_real: [0.07401153, 1.0] | Discrim_l_fake: [0.18392539, 0.96428573] | Gan_l: [0.27249622, 0.9404762]
Epoch: 211 | Discrim_l_real: [0.07246488, 1.0] | Discrim_l_fake: [0.17102757, 0.9672619] | Gan_l: [0.27254674, 0.9464286]
Epoch: 212 | Discrim_l_real: [0.07144455, 1.0] | Discrim_l_fake: [0.18470202, 0.96428573] | Gan_l: [0.27546892, 0.9345238]
Epoch: 213 | Discrim_l_real: [0.07375814, 1.0] | Discrim_l_fake: [0.17536949, 0.96428573] | Gan_l: [0.26758972, 0.95535713]
Epoch: 214 | Discrim_l_real: [0.07588729, 1.0] | Discrim_l_fake: [0.18255903, 0.96130955] | Gan_l: [0.26558527, 0.9583333]
Epoch: 215 | Discrim_l_real: [0.07233903, 1.0] | Discrim_l_fake: [0.18419993, 0.9583333] | Gan_l: [0.27708673, 0.95238096]
Epoch: 216 | 

Epoch: 275 | Discrim_l_real: [0.055882722, 1.0] | Discrim_l_fake: [0.32448065, 0.875] | Gan_l: [0.17913017, 0.9970238]
Epoch: 276 | Discrim_l_real: [0.0581445, 1.0] | Discrim_l_fake: [0.27743033, 0.9375] | Gan_l: [0.17854282, 1.0]
Epoch: 277 | Discrim_l_real: [0.05506738, 1.0] | Discrim_l_fake: [0.2713875, 0.9375] | Gan_l: [0.18641031, 0.99404764]
Epoch: 278 | Discrim_l_real: [0.05602359, 1.0] | Discrim_l_fake: [0.27488136, 0.9375] | Gan_l: [0.18285559, 0.9970238]
Epoch: 279 | Discrim_l_real: [0.056992438, 1.0] | Discrim_l_fake: [0.28669026, 0.93154764] | Gan_l: [0.20007259, 0.99404764]
Epoch: 280 | Discrim_l_real: [0.055648256, 1.0] | Discrim_l_fake: [0.28040427, 0.9375] | Gan_l: [0.18200439, 0.9970238]
Epoch: 281 | Discrim_l_real: [0.051687505, 1.0] | Discrim_l_fake: [0.28639555, 0.9375] | Gan_l: [0.1817397, 0.9970238]
Epoch: 282 | Discrim_l_real: [0.056042336, 1.0] | Discrim_l_fake: [0.26111057, 0.9464286] | Gan_l: [0.17997462, 0.9970238]
Epoch: 283 | Discrim_l_real: [0.053110503, 1

Epoch: 347 | Discrim_l_real: [0.06068113, 1.0] | Discrim_l_fake: [0.34524855, 0.91964287] | Gan_l: [0.23468395, 0.99404764]
Epoch: 348 | Discrim_l_real: [0.06469803, 1.0] | Discrim_l_fake: [0.38409546, 0.88095236] | Gan_l: [0.22019681, 0.9970238]
Epoch: 349 | Discrim_l_real: [0.05871109, 1.0] | Discrim_l_fake: [0.38360554, 0.89880955] | Gan_l: [0.21954633, 0.9910714]
Epoch: 350 | Discrim_l_real: [0.062052097, 1.0] | Discrim_l_fake: [0.37533787, 0.9047619] | Gan_l: [0.21333444, 0.99404764]
Epoch: 351 | Discrim_l_real: [0.067324325, 1.0] | Discrim_l_fake: [0.364939, 0.9047619] | Gan_l: [0.21325986, 0.9970238]
Epoch: 352 | Discrim_l_real: [0.057571314, 1.0] | Discrim_l_fake: [0.4444179, 0.8333333] | Gan_l: [0.21945141, 0.9970238]
Epoch: 353 | Discrim_l_real: [0.059907515, 1.0] | Discrim_l_fake: [0.3825645, 0.8779762] | Gan_l: [0.22222018, 0.99404764]
Epoch: 354 | Discrim_l_real: [0.0686429, 1.0] | Discrim_l_fake: [0.4159613, 0.8660714] | Gan_l: [0.21523885, 0.9970238]
Epoch: 355 | Discrim

Epoch: 414 | Discrim_l_real: [0.13280942, 1.0] | Discrim_l_fake: [0.7744832, 0.52678573] | Gan_l: [0.20187618, 0.9880952]
Epoch: 415 | Discrim_l_real: [0.13908738, 1.0] | Discrim_l_fake: [0.823703, 0.52380955] | Gan_l: [0.20588021, 0.9880952]
Epoch: 416 | Discrim_l_real: [0.123570226, 1.0] | Discrim_l_fake: [0.6417291, 0.6577381] | Gan_l: [0.25196037, 0.9702381]
Epoch: 417 | Discrim_l_real: [0.1396068, 1.0] | Discrim_l_fake: [0.74627656, 0.5744048] | Gan_l: [0.21230835, 0.99404764]
Epoch: 418 | Discrim_l_real: [0.15308912, 1.0] | Discrim_l_fake: [0.821398, 0.5416667] | Gan_l: [0.20841959, 0.9910714]
Epoch: 419 | Discrim_l_real: [0.13679661, 1.0] | Discrim_l_fake: [0.8402567, 0.49702382] | Gan_l: [0.20293948, 0.99404764]
Epoch: 420 | Discrim_l_real: [0.1633353, 0.9970238] | Discrim_l_fake: [0.88409483, 0.46130952] | Gan_l: [0.2011252, 0.9910714]
Epoch: 421 | Discrim_l_real: [0.15194012, 0.9970238] | Discrim_l_fake: [0.8055487, 0.51785713] | Gan_l: [0.21867253, 0.9910714]
Epoch: 422 | Di

Epoch: 479 | Discrim_l_real: [0.2231964, 0.9910714] | Discrim_l_fake: [0.8102616, 0.3065476] | Gan_l: [0.6220786, 0.7470238]
Epoch: 480 | Discrim_l_real: [0.20756303, 0.99404764] | Discrim_l_fake: [0.7572986, 0.38690478] | Gan_l: [0.6638176, 0.68154764]
Epoch: 481 | Discrim_l_real: [0.2336267, 0.9880952] | Discrim_l_fake: [0.78607136, 0.3690476] | Gan_l: [0.65532273, 0.6666667]
Epoch: 482 | Discrim_l_real: [0.22470059, 0.97619045] | Discrim_l_fake: [0.83237916, 0.3125] | Gan_l: [0.6355564, 0.69345236]
Epoch: 483 | Discrim_l_real: [0.22887424, 0.9880952] | Discrim_l_fake: [0.8249478, 0.31547618] | Gan_l: [0.6527825, 0.67261904]
Epoch: 484 | Discrim_l_real: [0.22284067, 0.9910714] | Discrim_l_fake: [0.7796091, 0.37202382] | Gan_l: [0.67076707, 0.66369045]
Epoch: 485 | Discrim_l_real: [0.21527977, 0.9970238] | Discrim_l_fake: [0.81076294, 0.29761904] | Gan_l: [0.63291186, 0.71130955]
Epoch: 486 | Discrim_l_real: [0.22060578, 0.99404764] | Discrim_l_fake: [0.8013861, 0.3125] | Gan_l: [0.65

Epoch: 546 | Discrim_l_real: [0.12991396, 1.0] | Discrim_l_fake: [0.5126099, 0.9077381] | Gan_l: [0.94929, 0.110119045]
Epoch: 547 | Discrim_l_real: [0.12861387, 1.0] | Discrim_l_fake: [0.5564226, 0.89880955] | Gan_l: [0.88585955, 0.09821428]
Epoch: 548 | Discrim_l_real: [0.121405795, 1.0] | Discrim_l_fake: [0.5182159, 0.9285714] | Gan_l: [0.9556354, 0.08630952]
Epoch: 549 | Discrim_l_real: [0.1181572, 1.0] | Discrim_l_fake: [0.5211601, 0.91369045] | Gan_l: [0.941171, 0.110119045]
Epoch: 550 | Discrim_l_real: [0.12029366, 1.0] | Discrim_l_fake: [0.50373155, 0.92261904] | Gan_l: [0.9454487, 0.0952381]
Epoch: 551 | Discrim_l_real: [0.11807148, 1.0] | Discrim_l_fake: [0.52889365, 0.88988096] | Gan_l: [0.94289625, 0.0922619]
Epoch: 552 | Discrim_l_real: [0.11043026, 1.0] | Discrim_l_fake: [0.4914208, 0.9345238] | Gan_l: [0.9505003, 0.09821428]
Epoch: 553 | Discrim_l_real: [0.12895063, 1.0] | Discrim_l_fake: [0.5146698, 0.9077381] | Gan_l: [0.9526163, 0.10119048]
Epoch: 554 | Discrim_l_real

Epoch: 615 | Discrim_l_real: [0.06985585, 1.0] | Discrim_l_fake: [0.70974666, 0.46130952] | Gan_l: [0.64699817, 0.6845238]
Epoch: 616 | Discrim_l_real: [0.0790637, 1.0] | Discrim_l_fake: [0.72198594, 0.4940476] | Gan_l: [0.626132, 0.66964287]
Epoch: 617 | Discrim_l_real: [0.07003106, 1.0] | Discrim_l_fake: [0.74273247, 0.41964287] | Gan_l: [0.61821073, 0.67261904]
Epoch: 618 | Discrim_l_real: [0.068713956, 1.0] | Discrim_l_fake: [0.7042311, 0.55654764] | Gan_l: [0.6640347, 0.5833333]
Epoch: 619 | Discrim_l_real: [0.06901405, 1.0] | Discrim_l_fake: [0.7407083, 0.5] | Gan_l: [0.62460166, 0.6785714]
Epoch: 620 | Discrim_l_real: [0.06396052, 1.0] | Discrim_l_fake: [0.7089044, 0.54464287] | Gan_l: [0.64682704, 0.6220238]
Epoch: 621 | Discrim_l_real: [0.072279796, 1.0] | Discrim_l_fake: [0.75929874, 0.41369048] | Gan_l: [0.63192266, 0.6160714]
Epoch: 622 | Discrim_l_real: [0.07537103, 1.0] | Discrim_l_fake: [0.76630837, 0.43452382] | Gan_l: [0.6184485, 0.67261904]
Epoch: 623 | Discrim_l_real

Epoch: 682 | Discrim_l_real: [0.068483844, 0.9970238] | Discrim_l_fake: [0.6510191, 0.58928573] | Gan_l: [0.66913897, 0.6130952]
Epoch: 683 | Discrim_l_real: [0.063873865, 1.0] | Discrim_l_fake: [0.6560654, 0.57738096] | Gan_l: [0.6964491, 0.61011904]
Epoch: 684 | Discrim_l_real: [0.07972068, 0.9910714] | Discrim_l_fake: [0.61319107, 0.66071427] | Gan_l: [0.7137029, 0.59821427]
Epoch: 685 | Discrim_l_real: [0.07018026, 1.0] | Discrim_l_fake: [0.6456961, 0.58630955] | Gan_l: [0.65868187, 0.6547619]
Epoch: 686 | Discrim_l_real: [0.07123187, 0.9970238] | Discrim_l_fake: [0.61586684, 0.6160714] | Gan_l: [0.73121065, 0.56845236]
Epoch: 687 | Discrim_l_real: [0.06814505, 0.9970238] | Discrim_l_fake: [0.59973615, 0.7202381] | Gan_l: [0.75759137, 0.52678573]
Epoch: 688 | Discrim_l_real: [0.07020557, 1.0] | Discrim_l_fake: [0.5612484, 0.8244048] | Gan_l: [0.77108353, 0.5297619]
Epoch: 689 | Discrim_l_real: [0.071928784, 0.9910714] | Discrim_l_fake: [0.593114, 0.7083333] | Gan_l: [0.70705014, 0.

Epoch: 747 | Discrim_l_real: [0.05839191, 0.9970238] | Discrim_l_fake: [0.3003428, 0.97321427] | Gan_l: [1.3454945, 0.032738097]
Epoch: 748 | Discrim_l_real: [0.04984376, 1.0] | Discrim_l_fake: [0.29598713, 0.9702381] | Gan_l: [1.3771878, 0.032738097]
Epoch: 749 | Discrim_l_real: [0.06665287, 0.9910714] | Discrim_l_fake: [0.28478652, 0.9791667] | Gan_l: [1.4082346, 0.023809524]
Epoch: 750 | Discrim_l_real: [0.054856155, 0.9970238] | Discrim_l_fake: [0.28317863, 0.9702381] | Gan_l: [1.4065653, 0.032738097]
Epoch: 751 | Discrim_l_real: [0.055139363, 0.9970238] | Discrim_l_fake: [0.28443703, 0.96130955] | Gan_l: [1.4423888, 0.038690478]
Epoch: 752 | Discrim_l_real: [0.06085804, 0.9910714] | Discrim_l_fake: [0.30621266, 0.95535713] | Gan_l: [1.3984656, 0.04761905]
Epoch: 753 | Discrim_l_real: [0.067279115, 0.9880952] | Discrim_l_fake: [0.28155887, 0.97619045] | Gan_l: [1.4140165, 0.020833334]
Epoch: 754 | Discrim_l_real: [0.061017096, 0.9910714] | Discrim_l_fake: [0.26071364, 0.98511904] |

Epoch: 813 | Discrim_l_real: [0.04300701, 0.99404764] | Discrim_l_fake: [0.21261425, 0.98511904] | Gan_l: [1.5058059, 0.032738097]
Epoch: 814 | Discrim_l_real: [0.046269115, 0.9970238] | Discrim_l_fake: [0.22455972, 0.97619045] | Gan_l: [1.5131141, 0.026785715]
Epoch: 815 | Discrim_l_real: [0.039910737, 1.0] | Discrim_l_fake: [0.21859854, 0.98214287] | Gan_l: [1.4945377, 0.026785715]
Epoch: 816 | Discrim_l_real: [0.044550672, 0.9970238] | Discrim_l_fake: [0.2165389, 0.97619045] | Gan_l: [1.5004549, 0.017857144]
Epoch: 817 | Discrim_l_real: [0.04175891, 0.9970238] | Discrim_l_fake: [0.20521417, 0.97321427] | Gan_l: [1.5447942, 0.017857144]
Epoch: 818 | Discrim_l_real: [0.043305364, 1.0] | Discrim_l_fake: [0.2187978, 0.9672619] | Gan_l: [1.5105197, 0.023809524]
Epoch: 819 | Discrim_l_real: [0.04199396, 0.9970238] | Discrim_l_fake: [0.223629, 0.9583333] | Gan_l: [1.5308491, 0.032738097]
Epoch: 820 | Discrim_l_real: [0.040848047, 1.0] | Discrim_l_fake: [0.22004797, 0.97619045] | Gan_l: [1.

Epoch: 880 | Discrim_l_real: [0.034088742, 0.9970238] | Discrim_l_fake: [0.14395006, 0.99404764] | Gan_l: [1.9778986, 0.0029761905]
Epoch: 881 | Discrim_l_real: [0.03421439, 0.9970238] | Discrim_l_fake: [0.1344807, 1.0] | Gan_l: [1.9625174, 0.0029761905]
Epoch: 882 | Discrim_l_real: [0.04109661, 0.9910714] | Discrim_l_fake: [0.15989868, 0.98214287] | Gan_l: [1.9195902, 0.017857144]
Epoch: 883 | Discrim_l_real: [0.03485527, 1.0] | Discrim_l_fake: [0.14646013, 0.99404764] | Gan_l: [1.9559894, 0.0029761905]
Epoch: 884 | Discrim_l_real: [0.034618486, 0.99404764] | Discrim_l_fake: [0.13463023, 0.99404764] | Gan_l: [2.0237322, 0.0029761905]
Epoch: 885 | Discrim_l_real: [0.036008716, 0.9970238] | Discrim_l_fake: [0.13806376, 0.99404764] | Gan_l: [1.9918392, 0.0029761905]
Epoch: 886 | Discrim_l_real: [0.036664132, 0.9970238] | Discrim_l_fake: [0.14013152, 0.99404764] | Gan_l: [2.0020692, 0.0029761905]
Epoch: 887 | Discrim_l_real: [0.037223242, 0.9910714] | Discrim_l_fake: [0.12864114, 0.997023

Epoch: 948 | Discrim_l_real: [0.02690656, 1.0] | Discrim_l_fake: [0.107906386, 0.9791667] | Gan_l: [2.400025, 0.029761905]
Epoch: 949 | Discrim_l_real: [0.025947206, 1.0] | Discrim_l_fake: [0.099760786, 0.9880952] | Gan_l: [2.4062407, 0.020833334]
Epoch: 950 | Discrim_l_real: [0.028881226, 1.0] | Discrim_l_fake: [0.09321164, 0.9880952] | Gan_l: [2.4501522, 0.017857144]
Epoch: 951 | Discrim_l_real: [0.02512934, 1.0] | Discrim_l_fake: [0.11233615, 0.9791667] | Gan_l: [2.3866417, 0.026785715]
Epoch: 952 | Discrim_l_real: [0.023343964, 1.0] | Discrim_l_fake: [0.11102982, 0.97321427] | Gan_l: [2.4233594, 0.041666668]
Epoch: 953 | Discrim_l_real: [0.023303447, 1.0] | Discrim_l_fake: [0.10272749, 0.98214287] | Gan_l: [2.4105008, 0.020833334]
Epoch: 954 | Discrim_l_real: [0.025423294, 1.0] | Discrim_l_fake: [0.1135226, 0.98214287] | Gan_l: [2.3654277, 0.020833334]
Epoch: 955 | Discrim_l_real: [0.023884507, 1.0] | Discrim_l_fake: [0.1071187, 0.9910714] | Gan_l: [2.3671298, 0.023809524]
Epoch: 9

Epoch: 1015 | Discrim_l_real: [0.032485764, 1.0] | Discrim_l_fake: [0.14653942, 0.9791667] | Gan_l: [2.3204355, 0.020833334]
Epoch: 1016 | Discrim_l_real: [0.028342096, 1.0] | Discrim_l_fake: [0.16950305, 0.95535713] | Gan_l: [2.2821, 0.038690478]
Epoch: 1017 | Discrim_l_real: [0.03075817, 1.0] | Discrim_l_fake: [0.182174, 0.94345236] | Gan_l: [2.277798, 0.04464286]
Epoch: 1018 | Discrim_l_real: [0.030601101, 1.0] | Discrim_l_fake: [0.15657625, 0.96428573] | Gan_l: [2.2924135, 0.026785715]
Epoch: 1019 | Discrim_l_real: [0.03510409, 1.0] | Discrim_l_fake: [0.14224787, 0.97619045] | Gan_l: [2.33783, 0.014880952]
Epoch: 1020 | Discrim_l_real: [0.027788868, 1.0] | Discrim_l_fake: [0.17789249, 0.95238096] | Gan_l: [2.2939503, 0.04464286]
Epoch: 1021 | Discrim_l_real: [0.03123397, 1.0] | Discrim_l_fake: [0.19081269, 0.9345238] | Gan_l: [2.2596474, 0.05654762]
Epoch: 1022 | Discrim_l_real: [0.030628525, 1.0] | Discrim_l_fake: [0.17355737, 0.95535713] | Gan_l: [2.3407738, 0.041666668]
Epoch: 1

Epoch: 1084 | Discrim_l_real: [0.032949254, 1.0] | Discrim_l_fake: [0.29316828, 0.9494048] | Gan_l: [1.7529496, 0.05357143]
Epoch: 1085 | Discrim_l_real: [0.03674311, 1.0] | Discrim_l_fake: [0.31756052, 0.91964287] | Gan_l: [1.6193142, 0.104166664]
Epoch: 1086 | Discrim_l_real: [0.034727577, 1.0] | Discrim_l_fake: [0.2800495, 0.9345238] | Gan_l: [1.6375498, 0.10119048]
Epoch: 1087 | Discrim_l_real: [0.036032636, 1.0] | Discrim_l_fake: [0.31439716, 0.9166667] | Gan_l: [1.6351748, 0.08035714]
Epoch: 1088 | Discrim_l_real: [0.035900842, 1.0] | Discrim_l_fake: [0.2686938, 0.9464286] | Gan_l: [1.6467263, 0.10119048]
Epoch: 1089 | Discrim_l_real: [0.03259633, 1.0] | Discrim_l_fake: [0.31115785, 0.92261904] | Gan_l: [1.6948483, 0.09821428]
Epoch: 1090 | Discrim_l_real: [0.03788302, 1.0] | Discrim_l_fake: [0.3382885, 0.88095236] | Gan_l: [1.5957677, 0.125]
Epoch: 1091 | Discrim_l_real: [0.03585516, 1.0] | Discrim_l_fake: [0.27008978, 0.94345236] | Gan_l: [1.6940273, 0.071428575]
Epoch: 1092 | 

Epoch: 1153 | Discrim_l_real: [0.028212862, 1.0] | Discrim_l_fake: [0.2271859, 0.98511904] | Gan_l: [1.5285659, 0.0029761905]
Epoch: 1154 | Discrim_l_real: [0.027979674, 1.0] | Discrim_l_fake: [0.2254404, 0.97321427] | Gan_l: [1.5732325, 0.0029761905]
Epoch: 1155 | Discrim_l_real: [0.031539913, 1.0] | Discrim_l_fake: [0.20215742, 0.99404764] | Gan_l: [1.6094872, 0.0]
Epoch: 1156 | Discrim_l_real: [0.032390397, 1.0] | Discrim_l_fake: [0.20202014, 0.9791667] | Gan_l: [1.6148827, 0.0]
Epoch: 1157 | Discrim_l_real: [0.027223563, 1.0] | Discrim_l_fake: [0.18909541, 0.9970238] | Gan_l: [1.6937001, 0.0]
Epoch: 1158 | Discrim_l_real: [0.025402207, 1.0] | Discrim_l_fake: [0.19063075, 0.99404764] | Gan_l: [1.6650186, 0.0]
Epoch: 1159 | Discrim_l_real: [0.025984142, 1.0] | Discrim_l_fake: [0.18526947, 0.9791667] | Gan_l: [1.7082977, 0.0]
Epoch: 1160 | Discrim_l_real: [0.025790552, 1.0] | Discrim_l_fake: [0.18097499, 0.98511904] | Gan_l: [1.7097816, 0.0]
Epoch: 1161 | Discrim_l_real: [0.02594006, 

Epoch: 1227 | Discrim_l_real: [0.015988817, 1.0] | Discrim_l_fake: [0.06740454, 1.0] | Gan_l: [2.0439436, 0.0]
Epoch: 1228 | Discrim_l_real: [0.01821179, 1.0] | Discrim_l_fake: [0.05949323, 1.0] | Gan_l: [2.226238, 0.0]
Epoch: 1229 | Discrim_l_real: [0.016121516, 1.0] | Discrim_l_fake: [0.056129426, 1.0] | Gan_l: [2.1280544, 0.0]
Epoch: 1230 | Discrim_l_real: [0.01689248, 1.0] | Discrim_l_fake: [0.0723482, 1.0] | Gan_l: [2.0911887, 0.0]
Epoch: 1231 | Discrim_l_real: [0.015808547, 1.0] | Discrim_l_fake: [0.0749089, 1.0] | Gan_l: [2.1149504, 0.0]
Epoch: 1232 | Discrim_l_real: [0.017534828, 1.0] | Discrim_l_fake: [0.071428925, 1.0] | Gan_l: [2.1166592, 0.0]
Epoch: 1233 | Discrim_l_real: [0.015901798, 1.0] | Discrim_l_fake: [0.05978452, 1.0] | Gan_l: [2.1579418, 0.0]
Epoch: 1234 | Discrim_l_real: [0.016066145, 1.0] | Discrim_l_fake: [0.06366254, 1.0] | Gan_l: [2.178263, 0.0]
Epoch: 1235 | Discrim_l_real: [0.016982669, 1.0] | Discrim_l_fake: [0.055954542, 1.0] | Gan_l: [2.1872816, 0.0]
Epoc

Epoch: 1301 | Discrim_l_real: [0.011959598, 1.0] | Discrim_l_fake: [0.04903663, 1.0] | Gan_l: [2.1372614, 0.0]
Epoch: 1302 | Discrim_l_real: [0.011778638, 1.0] | Discrim_l_fake: [0.03686058, 1.0] | Gan_l: [2.3019621, 0.0029761905]
Epoch: 1303 | Discrim_l_real: [0.011506385, 1.0] | Discrim_l_fake: [0.04983013, 0.9970238] | Gan_l: [2.170549, 0.0029761905]
Epoch: 1304 | Discrim_l_real: [0.010836844, 1.0] | Discrim_l_fake: [0.037625752, 1.0] | Gan_l: [2.305058, 0.005952381]
Epoch: 1305 | Discrim_l_real: [0.011532567, 1.0] | Discrim_l_fake: [0.04336357, 0.99404764] | Gan_l: [2.06605, 0.005952381]
Epoch: 1306 | Discrim_l_real: [0.01265246, 1.0] | Discrim_l_fake: [0.04901461, 0.9910714] | Gan_l: [2.1694353, 0.008928572]
Epoch: 1307 | Discrim_l_real: [0.01131155, 1.0] | Discrim_l_fake: [0.043046422, 0.99404764] | Gan_l: [2.2114565, 0.005952381]
Epoch: 1308 | Discrim_l_real: [0.011134854, 1.0] | Discrim_l_fake: [0.054214895, 0.9910714] | Gan_l: [2.1355383, 0.014880952]
Epoch: 1309 | Discrim_l_r

Epoch: 1370 | Discrim_l_real: [0.011744421, 1.0] | Discrim_l_fake: [0.051701747, 1.0] | Gan_l: [2.1400394, 0.0]
Epoch: 1371 | Discrim_l_real: [0.010687547, 1.0] | Discrim_l_fake: [0.05253545, 1.0] | Gan_l: [2.2007458, 0.0]
Epoch: 1372 | Discrim_l_real: [0.010520087, 1.0] | Discrim_l_fake: [0.061019305, 0.9880952] | Gan_l: [2.1552033, 0.008928572]
Epoch: 1373 | Discrim_l_real: [0.010437306, 1.0] | Discrim_l_fake: [0.056207336, 1.0] | Gan_l: [2.1811273, 0.0]
Epoch: 1374 | Discrim_l_real: [0.010535084, 1.0] | Discrim_l_fake: [0.056684762, 0.9970238] | Gan_l: [2.2445457, 0.0]
Epoch: 1375 | Discrim_l_real: [0.010307585, 1.0] | Discrim_l_fake: [0.0689616, 0.9970238] | Gan_l: [2.1866555, 0.0]
Epoch: 1376 | Discrim_l_real: [0.011565591, 1.0] | Discrim_l_fake: [0.07224366, 0.9910714] | Gan_l: [2.1750731, 0.0029761905]
Epoch: 1377 | Discrim_l_real: [0.010954792, 1.0] | Discrim_l_fake: [0.071968906, 0.9970238] | Gan_l: [2.1934624, 0.0]
Epoch: 1378 | Discrim_l_real: [0.011135422, 1.0] | Discrim_l_

Epoch: 1443 | Discrim_l_real: [0.007121455, 1.0] | Discrim_l_fake: [0.053027038, 1.0] | Gan_l: [2.443128, 0.0]
Epoch: 1444 | Discrim_l_real: [0.0072868103, 1.0] | Discrim_l_fake: [0.052771438, 1.0] | Gan_l: [2.3129528, 0.0]
Epoch: 1445 | Discrim_l_real: [0.0070250425, 1.0] | Discrim_l_fake: [0.047224555, 1.0] | Gan_l: [2.0288765, 0.0]
Epoch: 1446 | Discrim_l_real: [0.006649268, 1.0] | Discrim_l_fake: [0.034333937, 1.0] | Gan_l: [2.1672468, 0.0]
Epoch: 1447 | Discrim_l_real: [0.007600084, 1.0] | Discrim_l_fake: [0.034046337, 1.0] | Gan_l: [2.1004477, 0.0]
Epoch: 1448 | Discrim_l_real: [0.0072695636, 1.0] | Discrim_l_fake: [0.026130654, 1.0] | Gan_l: [2.0032835, 0.0]
Epoch: 1449 | Discrim_l_real: [0.006831474, 1.0] | Discrim_l_fake: [0.029994793, 1.0] | Gan_l: [2.3195674, 0.0]
Epoch: 1450 | Discrim_l_real: [0.0073265946, 1.0] | Discrim_l_fake: [0.026138736, 1.0] | Gan_l: [2.0118124, 0.0]
Epoch: 1451 | Discrim_l_real: [0.007823645, 1.0] | Discrim_l_fake: [0.02480759, 1.0] | Gan_l: [1.8876

Epoch: 1519 | Discrim_l_real: [0.0064901207, 1.0] | Discrim_l_fake: [0.020505503, 1.0] | Gan_l: [3.7048612, 0.0]
Epoch: 1520 | Discrim_l_real: [0.0061107795, 1.0] | Discrim_l_fake: [0.0188655, 1.0] | Gan_l: [3.7936287, 0.0]
Epoch: 1521 | Discrim_l_real: [0.006310979, 1.0] | Discrim_l_fake: [0.01712587, 1.0] | Gan_l: [3.8013997, 0.0]
Epoch: 1522 | Discrim_l_real: [0.005614406, 1.0] | Discrim_l_fake: [0.016984519, 1.0] | Gan_l: [3.5804713, 0.0]
Epoch: 1523 | Discrim_l_real: [0.006331358, 1.0] | Discrim_l_fake: [0.015617286, 1.0] | Gan_l: [3.8888106, 0.0]
Epoch: 1524 | Discrim_l_real: [0.005684539, 1.0] | Discrim_l_fake: [0.020453406, 1.0] | Gan_l: [3.6774898, 0.0]
Epoch: 1525 | Discrim_l_real: [0.0054743737, 1.0] | Discrim_l_fake: [0.018470898, 1.0] | Gan_l: [3.739606, 0.0]
Epoch: 1526 | Discrim_l_real: [0.005675341, 1.0] | Discrim_l_fake: [0.020469109, 1.0] | Gan_l: [3.7225218, 0.0]
Epoch: 1527 | Discrim_l_real: [0.0057288995, 1.0] | Discrim_l_fake: [0.020028373, 1.0] | Gan_l: [3.533951

Epoch: 1596 | Discrim_l_real: [0.00537349, 1.0] | Discrim_l_fake: [0.08600385, 1.0] | Gan_l: [2.8676584, 0.0]
Epoch: 1597 | Discrim_l_real: [0.005247015, 1.0] | Discrim_l_fake: [0.07979333, 1.0] | Gan_l: [2.8321962, 0.0]
Epoch: 1598 | Discrim_l_real: [0.005372976, 1.0] | Discrim_l_fake: [0.07559375, 1.0] | Gan_l: [2.8318725, 0.0]
Epoch: 1599 | Discrim_l_real: [0.0051839342, 1.0] | Discrim_l_fake: [0.06942917, 1.0] | Gan_l: [2.9199502, 0.0]
Epoch: 1600 | Discrim_l_real: [0.005359746, 1.0] | Discrim_l_fake: [0.09611909, 1.0] | Gan_l: [2.9334524, 0.0]
Epoch: 1601 | Discrim_l_real: [0.005306512, 1.0] | Discrim_l_fake: [0.06943171, 1.0] | Gan_l: [2.8175101, 0.0]
Epoch: 1602 | Discrim_l_real: [0.005200696, 1.0] | Discrim_l_fake: [0.06626572, 1.0] | Gan_l: [3.0015163, 0.0]
Epoch: 1603 | Discrim_l_real: [0.005281512, 1.0] | Discrim_l_fake: [0.08299723, 1.0] | Gan_l: [2.9499638, 0.0]
Epoch: 1604 | Discrim_l_real: [0.005380721, 1.0] | Discrim_l_fake: [0.08326144, 1.0] | Gan_l: [2.8866892, 0.0]
E

Epoch: 1672 | Discrim_l_real: [0.006096985, 1.0] | Discrim_l_fake: [0.106221385, 1.0] | Gan_l: [2.5059218, 0.0]
Epoch: 1673 | Discrim_l_real: [0.0052850395, 1.0] | Discrim_l_fake: [0.101333424, 1.0] | Gan_l: [2.6278048, 0.0]
Epoch: 1674 | Discrim_l_real: [0.0049842675, 1.0] | Discrim_l_fake: [0.11958695, 1.0] | Gan_l: [2.5682156, 0.0]
Epoch: 1675 | Discrim_l_real: [0.0055160527, 1.0] | Discrim_l_fake: [0.105815865, 1.0] | Gan_l: [2.62022, 0.0]
Epoch: 1676 | Discrim_l_real: [0.0047487956, 1.0] | Discrim_l_fake: [0.097694196, 1.0] | Gan_l: [2.6886814, 0.0]
Epoch: 1677 | Discrim_l_real: [0.0054657273, 1.0] | Discrim_l_fake: [0.09522872, 1.0] | Gan_l: [2.6346405, 0.0]
Epoch: 1678 | Discrim_l_real: [0.0055034016, 1.0] | Discrim_l_fake: [0.100197926, 1.0] | Gan_l: [2.5150623, 0.0]
Epoch: 1679 | Discrim_l_real: [0.005382475, 1.0] | Discrim_l_fake: [0.09875714, 1.0] | Gan_l: [2.7151113, 0.0]
Epoch: 1680 | Discrim_l_real: [0.0049869246, 1.0] | Discrim_l_fake: [0.10418076, 1.0] | Gan_l: [2.74905

Epoch: 1748 | Discrim_l_real: [0.005973204, 1.0] | Discrim_l_fake: [0.04378879, 1.0] | Gan_l: [3.702809, 0.0]
Epoch: 1749 | Discrim_l_real: [0.0056350767, 1.0] | Discrim_l_fake: [0.063913986, 1.0] | Gan_l: [2.938424, 0.0]
Epoch: 1750 | Discrim_l_real: [0.005523501, 1.0] | Discrim_l_fake: [0.06551433, 1.0] | Gan_l: [3.0087337, 0.0]
Epoch: 1751 | Discrim_l_real: [0.0055113453, 1.0] | Discrim_l_fake: [0.047684643, 1.0] | Gan_l: [3.4955328, 0.0]
Epoch: 1752 | Discrim_l_real: [0.0063020275, 1.0] | Discrim_l_fake: [0.0554511, 1.0] | Gan_l: [3.053021, 0.0]
Epoch: 1753 | Discrim_l_real: [0.0065964153, 1.0] | Discrim_l_fake: [0.05094529, 1.0] | Gan_l: [3.193574, 0.0]
Epoch: 1754 | Discrim_l_real: [0.005460408, 1.0] | Discrim_l_fake: [0.06532277, 1.0] | Gan_l: [3.0606492, 0.0]
Epoch: 1755 | Discrim_l_real: [0.0054520057, 1.0] | Discrim_l_fake: [0.05255044, 1.0] | Gan_l: [3.2158673, 0.0]
Epoch: 1756 | Discrim_l_real: [0.0059833876, 1.0] | Discrim_l_fake: [0.06751119, 1.0] | Gan_l: [2.9237578, 0.0

Epoch: 1821 | Discrim_l_real: [0.0061886795, 1.0] | Discrim_l_fake: [0.057387587, 1.0] | Gan_l: [2.3223398, 0.0]
Epoch: 1822 | Discrim_l_real: [0.0069625257, 1.0] | Discrim_l_fake: [0.06216649, 1.0] | Gan_l: [2.3760455, 0.0029761905]
Epoch: 1823 | Discrim_l_real: [0.0056630666, 1.0] | Discrim_l_fake: [0.067120634, 1.0] | Gan_l: [2.3795702, 0.0029761905]
Epoch: 1824 | Discrim_l_real: [0.0066292016, 1.0] | Discrim_l_fake: [0.05487896, 1.0] | Gan_l: [2.31841, 0.008928572]
Epoch: 1825 | Discrim_l_real: [0.006616801, 1.0] | Discrim_l_fake: [0.0597644, 0.9880952] | Gan_l: [2.4528172, 0.020833334]
Epoch: 1826 | Discrim_l_real: [0.006250525, 1.0] | Discrim_l_fake: [0.04565004, 1.0] | Gan_l: [2.655286, 0.008928572]
Epoch: 1827 | Discrim_l_real: [0.00576108, 1.0] | Discrim_l_fake: [0.04448322, 1.0] | Gan_l: [2.3689961, 0.008928572]
Epoch: 1828 | Discrim_l_real: [0.0057256743, 1.0] | Discrim_l_fake: [0.05753139, 1.0] | Gan_l: [2.4161406, 0.0029761905]
Epoch: 1829 | Discrim_l_real: [0.0056432174, 

Epoch: 1893 | Discrim_l_real: [0.0047602654, 1.0] | Discrim_l_fake: [0.078998595, 1.0] | Gan_l: [1.5451893, 0.0029761905]
Epoch: 1894 | Discrim_l_real: [0.0070122406, 1.0] | Discrim_l_fake: [0.085653976, 1.0] | Gan_l: [1.5402277, 0.026785715]
Epoch: 1895 | Discrim_l_real: [0.0067073437, 1.0] | Discrim_l_fake: [0.09025468, 1.0] | Gan_l: [1.6225216, 0.005952381]
Epoch: 1896 | Discrim_l_real: [0.006659139, 1.0] | Discrim_l_fake: [0.09480942, 1.0] | Gan_l: [1.6700914, 0.005952381]
Epoch: 1897 | Discrim_l_real: [0.0057918928, 1.0] | Discrim_l_fake: [0.09673018, 1.0] | Gan_l: [1.6622778, 0.011904762]
Epoch: 1898 | Discrim_l_real: [0.0059952755, 1.0] | Discrim_l_fake: [0.08917055, 1.0] | Gan_l: [1.7686127, 0.0]
Epoch: 1899 | Discrim_l_real: [0.0062391683, 1.0] | Discrim_l_fake: [0.094347745, 1.0] | Gan_l: [1.9939342, 0.0]
Epoch: 1900 | Discrim_l_real: [0.0072141355, 1.0] | Discrim_l_fake: [0.11161062, 1.0] | Gan_l: [1.7873677, 0.0]
Epoch: 1901 | Discrim_l_real: [0.0101718735, 1.0] | Discrim_l

Epoch: 1965 | Discrim_l_real: [0.0155382855, 1.0] | Discrim_l_fake: [0.13481733, 0.9910714] | Gan_l: [2.8801537, 0.011904762]
Epoch: 1966 | Discrim_l_real: [0.015590775, 1.0] | Discrim_l_fake: [0.1144641, 1.0] | Gan_l: [2.4047008, 0.0]
Epoch: 1967 | Discrim_l_real: [0.015554632, 1.0] | Discrim_l_fake: [0.10371145, 0.9970238] | Gan_l: [2.6922357, 0.017857144]
Epoch: 1968 | Discrim_l_real: [0.01843915, 1.0] | Discrim_l_fake: [0.10523837, 0.99404764] | Gan_l: [2.6298318, 0.011904762]
Epoch: 1969 | Discrim_l_real: [0.018883584, 1.0] | Discrim_l_fake: [0.13034353, 0.9970238] | Gan_l: [3.0324287, 0.014880952]
Epoch: 1970 | Discrim_l_real: [0.016242715, 1.0] | Discrim_l_fake: [0.10123487, 0.9970238] | Gan_l: [2.7572107, 0.008928572]
Epoch: 1971 | Discrim_l_real: [0.0112307705, 1.0] | Discrim_l_fake: [0.08437238, 1.0] | Gan_l: [2.782087, 0.026785715]
Epoch: 1972 | Discrim_l_real: [0.018652508, 1.0] | Discrim_l_fake: [0.09621767, 0.9970238] | Gan_l: [2.881712, 0.011904762]
Epoch: 1973 | Discrim

### Statistical inference

#### Statistics of the data

In [207]:
mean_data = np.mean(processed_data, axis = 0)
variance_data = np.mean((processed_data - mean_data )* (processed_data- mean_data ), axis = 0)
skewness_data = np.mean((processed_data - mean_data )* (processed_data- mean_data ) * (processed_data- mean_data ), axis = 0)

In [208]:
print(mean_data)
print('------------')
print(variance_data)
print('------------')
print(skewness_data)

[[0.5        0.49547619 0.5014881 ]
 [0.50002976 0.50017857 0.        ]
 [0.         0.         0.        ]]
------------
[[0.02188512 0.00780811 0.00074183]
 [0.01493125 0.04641009 0.        ]
 [0.         0.         0.        ]]
------------
[[0.00249854 0.00381854 0.00036871]
 [0.00011419 0.00261314 0.        ]
 [0.         0.         0.        ]]


#### Statistics of the generated data

In [212]:
gaussian_noise= np.random.normal(0.5, 0.25, (batch_size, X_train.shape[1], X_train.shape[2], 1))
gen_data = np.squeeze(generator.predict(gaussian))

In [213]:
mean_gen_data = np.mean(gen_data, axis = 0)
variance_gen_data = np.mean((processed_data - mean_gen_data)* (processed_data- mean_gen_data), axis = 0)
skewness_gen_data = np.mean((processed_data - mean_gen_data)* (processed_data- mean_gen_data) * (processed_data- mean_gen_data), axis = 0)

In [214]:
print(mean_gen_data)
print('------------')
print(variance_gen_data)
print('------------')
print(skewness_gen_data)

[[-1.4671538e+00  3.8748941e-01  7.2248483e-01]
 [ 1.0245727e-01  1.8862639e-01  6.6277611e-01]
 [ 1.0929146e+00  2.5235547e-04 -5.1832271e-01]]
------------
[[3.89157914e+00 1.94692517e-02 4.95813887e-02]
 [1.72995135e-01 1.43474847e-01 4.39272175e-01]
 [1.19446228e+00 6.36832843e-08 2.68658428e-01]]
------------
[[ 7.74393598e+00  7.60730238e-03 -1.09165015e-02]
 [ 8.07648026e-02  7.62313658e-02 -2.91139105e-01]
 [-1.30544524e+00 -1.60708253e-11  1.39251763e-01]]
